name: 'bump'

on:
  push:
    branches: [ 'main' ]

jobs:
  bump:
    if: |
         !startsWith(github.event.head_commit.message, 'bump')
         && !startsWith(github.event.head_commit.message, 'ci')
         && !startsWith(github.event.head_commit.message, 'chore(release)')
         && !startsWith(github.event.head_commit.message, '[NO_PUB]')
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
      with:
        token: ${{ secrets.GH_TOKEN }}

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    # run `standard-version`
    # - update CHANGELOG,
    # - create version tag
    # - create version commits
    - name: 'update happi'
      run: |
        cd happi
        echo "updating Cargo.toml, CHANGELOG, src/lib.rs"
        npx standard-version
        echo "updating Cargo.lock"
        cargo check
        git add -A; git commit --no-edit --amend

    - name: 'update happi-derive'
      run: |
        cd happi-derive
        echo "updating Cargo.toml, CHANGELOG, src/lib.rs"
        npx standard-version
        echo "updating Cargo.lock"
        cargo check
        git add -A; git commit --no-edit --amend

    - run: 'git push --follow-tags;'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
