name: 'bump'

on:
  push:
    branches: [ 'main' ]

jobs:
  bump:
    if: |
         !startsWith(github.event.head_commit.message, 'bump')
         && !startsWith(github.event.head_commit.message, 'ci')
         && !startsWith(github.event.head_commit.message, 'chore(release)')
         && !startsWith(github.event.head_commit.message, '[NO_PUB]')
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
      with:
        token: ${{ secrets.GH_TOKEN }}

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    - name: bump & publish - happi-derive
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: |
        cd ../happi-derive
        echo "bumping Cargo.toml, CHANGELOG, src/lib.rs"
        npx standard-version
        echo "updating Cargo.lock"
        cargo check
        git add -A; git commit --no-edit --amend
        echo "publishing to crates.io"
        cargo publish

    - name: bump & publish - happi
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: |
        cd happi
        echo "bumping Cargo.toml, CHANGELOG, src/lib.rs, tagging repo"
        npx standard-version
        echo "publishing to crates.io"
        cargo publish
        echo "updating Cargo.lock"
        cargo check
        git add -A; git commit --no-edit --amend

    - name: release
      run: git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
