name: 'publish'

on:
  push:
    tags: ['*']

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - run: 'cd happi; cargo publish'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}

    - run: 'cd ../happi-derive; cargo publish'
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
