name: release

on:
  push:
    branches: [ 'main' ]

jobs:
  release:
    if: |
         !startsWith(github.event.head_commit.message, 'bump')
         && !startsWith(github.event.head_commit.message, 'ci')
         && !startsWith(github.event.head_commit.message, 'chore(release)')
         && !startsWith(github.event.head_commit.message, '[NO_PUB]')
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
      with:
        token: ${{ secrets.GH_TOKEN }}

    - run: |
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global user.name "${{ github.actor }}"

    - uses: actions/cache@v2
      with:
        path: |
          ~/.rustup
          ~/.cargo
          target
        key: ${{ runner.os }}-cargo

    - uses: 'actions/setup-node@v1'
      with: { node-version: '14' }

    - run: 'npm install'

    - name: release happi-derive
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: |
        cd happi-derive
        echo "bump Cargo.toml, CHANGELOG.md, src/lib.rs"
        npx standard-version
        echo "publish to crates.io"
        cargo publish --manifest-path ./Cargo.toml

    - name: release happi
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
      run: |
        cd happi
        echo "bump Cargo.toml, CHANGELOG.md, src/lib.rs + new tag"
        npx standard-version
        echo "publish to crates.io"
        cargo publish --manifest-path ./Cargo.toml

    - name: finalize repo changes
      run: |
        echo "update Cargo.lock"
        cargo check
        echo "amend chore(release) commit"
        git add -A; git commit --no-edit --amend

    - name: push repo changes
      run: git push --follow-tags
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
